// react-frontend-example/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [step, setStep] = useState('input'); // input, followup, complete
  const [patientData, setPatientData] = useState({
    name: '',
    age: '',
    gender: '',
    symptoms: ''
  });
  const [sessionId, setSessionId] = useState(null);
  const [question, setQuestion] = useState(null);
  const [options, setOptions] = useState([]);
  const [error, setError] = useState(null);
  const [socket, setSocket] = useState(null);

  // Handle input form changes
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setPatientData(prev => ({
      ...prev,
      [name]: name === 'age' ? parseInt(value) || '' : value
    }));
  };

  // Submit symptoms to start diagnosis
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);

    try {
      const response = await fetch('http://127.0.0.1:8000/symptom', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(patientData)
      });

      const data = await response.json();
      
      if (response.ok) {
        setSessionId(data.session_id);
        setStep('followup');
        connectToFollowup(data.session_id);
      } else {
        setError(data.detail || 'Error submitting symptoms');
      }
    } catch (error) {
      setError('Network error: ' + error.message);
    }
  };

  // Connect to WebSocket for followup questions
  const connectToFollowup = (sid) => {
    const ws = new WebSocket(`ws://127.0.0.1:8000/followup/${sid}`);
    
    ws.onopen = () => {
      console.log('WebSocket connected');
    };
    
    ws.onmessage = (event) => {
      const data = JSON.parse(event.data);
      
      if (data.status === 'waiting_for_answer') {
        setQuestion(data.question);
        setOptions(data.options);
      } else if (data.status === 'ready_for_diagnosis') {
        setStep('complete');
        ws.close();
      } else if (data.error) {
        setError(data.error);
      }
    };
    
    ws.onerror = (error) => {
      setError('WebSocket error: ' + error.message);
    };
    
    setSocket(ws);
  };

  // Submit answer to followup question
  const submitAnswer = (key) => {
    if (socket && socket.readyState === WebSocket.OPEN) {
      socket.send(key);
    }
  };

  // Download diagnosis report
  const downloadReport = () => {
    window.open(`http://127.0.0.1:8000/generate_report/${sessionId}`, '_blank');
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>Medical Diagnosis System</h1>
      </header>

      <main>
        {error && (
          <div className="error-container">
            <p className="error-message">{error}</p>
            <button onClick={() => setError(null)}>Dismiss</button>
          </div>
        )}

        {step === 'input' && (
          <div className="patient-form-container">
            <h2>Enter Patient Information</h2>
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label htmlFor="name">Full Name</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={patientData.name}
                  onChange={handleInputChange}
                  required
                />
              </div>

              <div className="form-group">
                <label htmlFor="age">Age</label>
                <input
                  type="number"
                  id="age"
                  name="age"
                  value={patientData.age}
                  onChange={handleInputChange}
                  required
                />
              </div>

              <div className="form-group">
                <label htmlFor="gender">Gender</label>
                <select
                  id="gender"
                  name="gender"
                  value={patientData.gender}
                  onChange={handleInputChange}
                  required
                >
                  <option value="">Select Gender</option>
                  <option value="male">Male</option>
                  <option value="female">Female</option>
                  <option value="other">Other</option>
                </select>
              </div>

              <div className="form-group">
                <label htmlFor="symptoms">Describe Your Symptoms</label>
                <textarea
                  id="symptoms"
                  name="symptoms"
                  value={patientData.symptoms}
                  onChange={handleInputChange}
                  rows="5"
                  required
                ></textarea>
              </div>

              <button type="submit" className="submit-button">Start Diagnosis</button>
            </form>
          </div>
        )}

        {step === 'followup' && (
          <div className="followup-container">
            <h2>Follow-up Questions</h2>
            {question && (
              <div className="question-container">
                <p className="question">{question}</p>
                <div className="options-container">
                  {options.map((option) => (
                    <button
                      key={option.key}
                      className="option-button"
                      onClick={() => submitAnswer(option.key)}
                    >
                      <span className="option-key">{option.key}</span>
                      <span className="option-value">{option.value}</span>
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {step === 'complete' && (
          <div className="complete-container">
            <h2>Diagnosis Complete</h2>
            <p>Thank you for using our Medical Diagnosis System.</p>
            <p>Your diagnosis report is ready.</p>
            <button onClick={downloadReport} className="download-button">
              Download Diagnosis Report
            </button>
            <button onClick={() => {
              setStep('input');
              setSessionId(null);
              setQuestion(null);
              setOptions([]);
              setPatientData({
                name: '',
                age: '',
                gender: '',
                symptoms: ''
              });
            }} className="new-diagnosis-button">
              Start New Diagnosis
            </button>
          </div>
        )}
      </main>
    </div>
  );
}

export default App;

// angular-frontend-example/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

interface PatientData {
  name: string;
  age: number;
  gender: string;
  symptoms: string;
}

interface Option {
  key: string;
  value: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
  title = 'Medical Diagnosis System';
  patientForm: FormGroup;
  currentView: 'input' | 'followup' | 'complete' = 'input';
  sessionId: string | null = null;
  question: string | null = null;
  options: Option[] = [];
  error: string | null = null;
  socket: WebSocket | null = null;
  
  private readonly API_URL = 'http://127.0.0.1:8000';

  constructor(
    private fb: FormBuilder,
    private http: HttpClient
  ) {
    this.patientForm = this.fb.group({
      name: ['', Validators.required],
      age: ['', [Validators.required, Validators.min(0), Validators.max(120)]],
      gender: ['', Validators.required],
      symptoms: ['', [Validators.required, Validators.minLength(10)]]
    });
  }

  ngOnInit(): void {
    // Initialize any resources if needed
  }

  ngOnDestroy(): void {
    // Close WebSocket connection if open
    if (this.socket) {
      this.socket.close();
    }
  }

  submitSymptoms(): void {
    if (this.patientForm.invalid) {
      this.markFormGroupTouched(this.patientForm);
      return;
    }

    this.error = null;
    
    const patientData: PatientData = {
      name: this.patientForm.value.name,
      age: this.patientForm.value.age,
      gender: this.patientForm.value.gender,
      symptoms: this.patientForm.value.symptoms
    };

    this.http.post<any>(`${this.API_URL}/symptom`, patientData)
      .subscribe({
        next: (response) => {
          this.sessionId = response.session_id;
          this.currentView = 'followup';
          this.connectToFollowup(response.session_id);
        },
        error: (error) => {
          this.error = error.error?.detail || 'Error submitting symptoms. Please try again.';
        }
      });
  }

  connectToFollowup(sessionId: string): void {
    this.socket = new WebSocket(`ws://127.0.0.1:8000/followup/${sessionId}`);
    
    this.socket.onopen = () => {
      console.log('WebSocket connected');
    };
    
    this.socket.onmessage = (event) => {
      const data = JSON.parse(event.data);
      
      if (data.status === 'waiting_for_answer') {
        this.question = data.question;
        this.options = data.options;
      } else if (data.status === 'ready_for_diagnosis') {
        this.currentView = 'complete';
        this.socket?.close();
        this.socket = null;
      } else if (data.error) {
        this.error = data.error;
      }
    };
    
    this.socket.onerror = (error) => {
      this.error = 'WebSocket error: Unable to connect to the diagnosis server.';
    };
  }

  submitAnswer(key: string): void {
    if (this.socket && this.socket.readyState === WebSocket.OPEN) {
      this.socket.send(key);
    }
  }

  downloadReport(): void {
    if (!this.sessionId) return;
    
    window.open(`${this.API_URL}/generate_report/${this.sessionId}`, '_blank');
  }

  startNewDiagnosis(): void {
    this.currentView = 'input';
    this.sessionId = null;
    this.question = null;
    this.options = [];
    this.patientForm.reset();
    
    if (this.socket) {
      this.socket.close();
      this.socket = null;
    }
  }

  dismissError(): void {
    this.error = null;
  }

  // Helper method to mark all controls as touched
  private markFormGroupTouched(formGroup: FormGroup): void {
    Object.values(formGroup.controls).forEach(control => {
      control.markAsTouched();
      
      if ((control as any).controls) {
        this.markFormGroupTouched(control as FormGroup);
      }
    });
  }
} 
<div class="medical-diagnosis-app">
  <header class="app-header">
    <h1>{{ title }}</h1>
  </header>

  <main>
    <!-- Error message -->
    <div *ngIf="error" class="error-container">
      <p class="error-message">{{ error }}</p>
      <button (click)="dismissError()" class="dismiss-button">Dismiss</button>
    </div>

    <!-- Patient Form View -->
    <div *ngIf="currentView === 'input'" class="patient-form-container">
      <h2>Enter Patient Information</h2>
      <form [formGroup]="patientForm" (ngSubmit)="submitSymptoms()">
        <div class="form-group">
          <label for="name">Full Name</label>
          <input 
            type="text" 
            id="name" 
            formControlName="name"
          >
          <div *ngIf="patientForm.get('name')?.touched && patientForm.get('name')?.errors?.['required']" class="error-text">
            Name is required
          </div>
        </div>

        <div class="form-group">
          <label for="age">Age</label>
          <input 
            type="number" 
            id="age" 
            formControlName="age"
          >
          <div *ngIf="patientForm.get('age')?.touched && patientForm.get('age')?.errors?.['required']" class="error-text">
            Age is required
          </div>
          <div *ngIf="patientForm.get('age')?.touched && patientForm.get('age')?.errors?.['min']" class="error-text">
            Age must be a positive number
          </div>
          <div *ngIf="patientForm.get('age')?.touched && patientForm.get('age')?.errors?.['max']" class="error-text">
            Age must be less than 120
          </div>
        </div>

        <div class="form-group">
          <label for="gender">Gender</label>
          <select 
            id="gender" 
            formControlName="gender"
          >
            <option value="">Select Gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Other</option>
          </select>
          <div *ngIf="patientForm.get('gender')?.touched && patientForm.get('gender')?.errors?.['required']" class="error-text">
            Gender is required
          </div>
        </div>

        <div class="form-group">
          <label for="symptoms">Describe Your Symptoms</label>
          <textarea 
            id="symptoms" 
            formControlName="symptoms" 
            rows="5"
          ></textarea>
          <div *ngIf="patientForm.get('symptoms')?.touched && patientForm.get('symptoms')?.errors?.['required']" class="error-text">
            Symptoms are required
          </div>
          <div *ngIf="patientForm.get('symptoms')?.touched && patientForm.get('symptoms')?.errors?.['minlength']" class="error-text">
            Please provide more details about your symptoms (at least 10 characters)
          </div>
        </div>

        <button type="submit" class="submit-button">Start Diagnosis</button>
      </form>
    </div>

    <!-- Follow-up Questions View -->
    <div *ngIf="currentView === 'followup'" class="followup-container">
      <h2>Follow-up Questions</h2>
      <div *ngIf="question" class="question-container">
        <p class="question">{{ question }}</p>
        <div class="options-container">
          <button 
            *ngFor="let option of options" 
            class="option-button"
            (click)="submitAnswer(option.key)"
          >
            <span class="option-key">{{ option.key }}</span>
            <span class="option-value">{{ option.value }}</span>
          </button>
        </div>
      </div>
    </div>

    <!-- Diagnosis Complete View -->
    <div *ngIf="currentView === 'complete'" class="complete-container">
      <h2>Diagnosis Complete</h2>
      <p>Thank you for using our Medical Diagnosis System.</p>
      <p>Your diagnosis report is ready.</p>
      <div class="actions">
        <button (click)="downloadReport()" class="download-button">
          Download Diagnosis Report
        </button>
        <button (click)="startNewDiagnosis()" class="new-diagnosis-button">
          Start New Diagnosis
        </button>
      </div>
    </div>
  </main>
</div>
